sonar.projectKey=software2024
sonar.projectName=Software2024
sonar.projectVersion=1.0
sonar.sources=app,routes,resources
sonar.tests=tests
sonar.language=php
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqp_2ebf7d37cb97c524a8210c1cca6031e1818ed55e
sonar.exclusions=public/storage/**,vendor/**,node_modules/**,bootstrap/cache/**,tests/bootstrap/**,tests/CreatesApplication.php,tests/Feature/**,tests/Unit/**,tests/TestCase.php
